# Generated by Django 2.1.2 on 2018-10-31 13:53

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Timestamp')),
                ('action', models.CharField(max_length=16, verbose_name='Action of entry')),
                ('user_repr', models.CharField(max_length=255, verbose_name='User (repr)')),
                ('content_type_repr', models.CharField(max_length=255, verbose_name='Content type (repr)')),
                ('object_id', models.TextField(blank=True, null=True, verbose_name='Object ID')),
                ('description', models.TextField(blank=True, verbose_name='Entry description')),
                ('payload', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Payload', blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType', verbose_name='Content type', related_name='+')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User', related_name='+')),
            ],
            options={
                'verbose_name': 'Journal entry',
                'verbose_name_plural': 'Journal entries',
                'ordering': ('-timestamp',),
            },
        ),
    ]
